services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - db_data:/data/hiero-db

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local

